export const footerStyles = {
  root: {
    background: '#000',
    color: '#fff',
    width: '100%',
    pt: { xs: 3, sm: 6 },
    pb: { xs: 1, sm: 2 },
    px: 0,
    fontFamily: 'Montserrat, sans-serif',
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  container: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: { xs: 'column', sm: 'row' },
    justifyContent: { xs: 'center', sm: 'space-between' },
    alignItems: { xs: 'center', sm: 'flex-start' },
    maxWidth: 1200,
    margin: '0 auto',
    gap: { xs: 2, sm: 4 },
    width: '100%',
    boxSizing: 'border-box',
    overflowX: 'hidden',
    textAlign: { xs: 'center', sm: 'left' },
  },
  logoCol: {
    flex: '1 1 240px',
    minWidth: 180,
    maxWidth: 320,
    mb: { xs: 2, sm: 4 },
    mt: 0,
    alignItems: { xs: 'center', sm: 'flex-start' },
    display: 'flex',
    flexDirection: 'column',
  },
  logo: {
    color: '#3CFFD0',
    fontFamily: 'Anton, sans-serif',
    fontWeight: 700,
    fontSize: { xs: 24, sm: 32 },
    mb: 2,
    mt: 0,
    textAlign: { xs: 'center', sm: 'left' },
  },
  desc: {
    color: '#bdbdbd',
    fontSize: { xs: 14, sm: 16 },
    mb: 3,
    lineHeight: 1.5,
    textAlign: { xs: 'center', sm: 'left' },
  },
  social: {
    display: 'flex',
    gap: 2,
    mt: 2,
    justifyContent: { xs: 'center', sm: 'flex-start' },
  },
  col: {
    flex: '1 1 140px',
    minWidth: 120,
    mb: { xs: 2, sm: 4 },
    mt: 0,
    alignItems: { xs: 'center', sm: 'flex-start' },
    display: 'flex',
    flexDirection: 'column',
  },
  colTitle: {
    fontWeight: 700,
    fontSize: { xs: 18, sm: 22 },
    mb: 2,
    mt: 0,
    fontFamily: 'Montserrat, sans-serif',
    textAlign: { xs: 'center', sm: 'left' },
  },
  link: {
    color: '#fff',
    textDecoration: 'none',
    fontSize: { xs: 14, sm: 16 },
    display: 'block',
    mb: 1,
    transition: 'color 0.2s',
    '&:hover': {
      color: '#3CFFD0',
    },
    textAlign: { xs: 'center', sm: 'left' },
  },
  subscribeCol: {
    flex: '1 1 240px',
    minWidth: 180,
    maxWidth: 320,
    mb: { xs: 2, sm: 4 },
    mt: 0,
    alignItems: { xs: 'center', sm: 'flex-start' },
    display: 'flex',
    flexDirection: 'column',
  },
  subscribeTitle: {
    fontWeight: 700,
    fontSize: { xs: 18, sm: 22 },
    mb: 2,
    mt: 0,
    fontFamily: 'Montserrat, sans-serif',
    textAlign: { xs: 'center', sm: 'left' },
  },
  subscribeBox: {
    display: 'flex',
    alignItems: 'center',
    mb: 2,
    mt: 1,
    flexDirection: { xs: 'column', sm: 'row' },
    gap: { xs: 1, sm: 0 },
  },
  subscribeInput: {
    flex: 1,
    background: '#222',
    border: 'none',
    outline: 'none',
    color: '#fff',
    fontSize: { xs: 16, sm: 18 },
    padding: { xs: '10px 12px', sm: '12px 16px' },
    borderRadius: 0,
    fontFamily: 'Montserrat, sans-serif',
    width: { xs: '100%', sm: 'auto' },
    mb: { xs: 1, sm: 0 },
  },
  subscribeBtn: {
    background: '#3CFFD0',
    border: 'none',
    minWidth: 50,
    height: 55,
    ml: { xs: 0, sm: 1 },
    color: '#181818',
    fontSize: 24,
    borderRadius: 0,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.2s',
    width: { xs: '100%', sm: 'auto' },
    '&:hover': {
      background: '#2ad1a3',
    },
  },
  subscribeCheckbox: {
    color: '#3CFFD0',
    mr: 1,
    '&.Mui-checked': {
      color: '#3CFFD0',
    },
  },
  subscribeLabel: {
    color: '#bdbdbd',
    fontSize: 15,
    fontFamily: 'Montserrat, sans-serif',
    textAlign: { xs: 'center', sm: 'left' },
  },
  bottomBar: {
    borderTop: '1px solid #222',
    mt: { xs: 2, sm: 4 },
    pt: { xs: 1, sm: 2 },
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: { xs: 'column', sm: 'row' },
    justifyContent: { xs: 'center', sm: 'space-between' },
    alignItems: { xs: 'center', sm: 'center' },
    fontSize: 15,
    color: '#bdbdbd',
    textAlign: { xs: 'center', sm: 'left' },
    gap: { xs: 1, sm: 0 },
  },
  bottomLinks: {
    display: 'flex',
    gap: 2,
    alignItems: 'center',
    fontSize: 15,
    color: '#bdbdbd',
    justifyContent: { xs: 'center', sm: 'flex-end' },
  },
  upArrow: {
    color: '#fff',
    fontSize: 32,
    ml: 2,
    cursor: 'pointer',
    transition: 'color 0.2s',
    '&:hover': {
      color: '#3CFFD0',
    },
  },
}; 