export const sideDrawerStyles = {
  drawer: {
    position: 'fixed',
    top: 0,
    right: 0,
    height: '100vh',
    width: { xs: '100vw', sm: 400 },
    bgcolor: '#181818',
    color: '#fff',
    zIndex: 2000,
    boxShadow: '-4px 0 24px rgba(0,0,0,0.3)',
    transform: 'translateX(100%)',
    transition: 'transform 0.5s cubic-bezier(0.77, 0, 0.175, 1)',
    display: 'flex',
    flexDirection: 'column',
    p: 0,
  },
  drawerOpen: {
    transform: 'translateX(0)',
    boxShadow: '-4px 0 24px rgba(0,0,0,0.3)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    p: { xs: 2, sm: 3 },
    pb: { xs: 1, sm: 2 },
  },
  logo: {
    color: '#3CFFD0',
    fontFamily: 'Anton, sans-serif',
    fontWeight: 700,
    fontSize: { xs: 24, sm: 32 },
  },
  closeIcon: {
    color: '#fff',
    fontSize: { xs: 28, sm: 36 },
  },
  newsList: {
    flex: 1,
    overflowY: 'auto',
    px: { xs: 2, sm: 3 },
  },
  newsCard: {
    display: 'flex',
    alignItems: 'flex-start',
    mb: 3,
  },
  newsAvatar: {
    width: 80,
    height: 80,
    mr: 2,
  },
  newsTitle: {
    fontFamily: 'Montserrat, sans-serif',
    fontWeight: 700,
    fontSize: 22,
    lineHeight: 1.2,
  },
  newsAuthor: {
    color: '#3CFFD0',
    fontWeight: 700,
    fontSize: 14,
    mt: 1,
    fontFamily: 'Montserrat, sans-serif',
    display: 'inline-block',
  },
  newsDate: {
    color: '#bdbdbd',
    fontSize: 14,
    ml: 1,
    fontFamily: 'Montserrat, sans-serif',
    display: 'inline-block',
  },
  divider: {
    bgcolor: '#333',
    my: 2,
  },
  socialIcons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 3,
    pb: 3,
  },
  socialIconBtn: {
    color: '#fff',
    fontSize: { xs: 22, sm: 28 },
  },
  filterSection: {
    mb: 3,
    mt: 3,
  },
  filterDatePicker: {
    '& .MuiInputBase-root': {
      color: '#fff',
      fontWeight: 500,
    },
    '& .MuiInputBase-input': {
      color: '#fff',
    },
    '& .MuiInputLabel-root': {
      color: '#fff',
    },
    '& .MuiSvgIcon-root': {
      color: '#fff',
    },
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: '#3CFFD0',
    },
    mb: 2,
    input: { color: '#fff' },
    label: { color: '#fff' },
    '.MuiInputBase-input::placeholder': { color: '#fff', opacity: 1 },
    fontSize: { xs: 16, sm: 18 },
  },
  filterChipGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: { xs: 0.5, sm: 1 },
  },
  filterChip: {
    backgroundColor: '#222',
    color: '#fff',
    fontWeight: 700,
    fontFamily: 'Montserrat, sans-serif',
    borderRadius: 1,
    fontSize: { xs: 13, sm: 15 },
    border: '2px solid #333',
    transition: 'all 0.2s',
    minHeight: { xs: 28, sm: 32 },
    px: { xs: 1, sm: 2 },
  },
  filterChipSelected: {
    backgroundColor: '#3CFFD0',
    color: '#181818',
    border: '2px solid #3CFFD0',
  },
  filterLabel: {
    color: '#fff',
    fontWeight: 500,
    mb: 1,
    fontSize: { xs: 13, sm: 15 },
  },
  filterButton: {
    mt: 2,
    borderColor: '#3CFFD0',
    color: '#fff',
    fontFamily: 'Anton, sans-serif',
    fontWeight: 700,
    fontSize: { xs: 16, sm: 20 },
    borderRadius: 0,
    boxShadow: 'none',
    background: 'transparent',
    textTransform: 'none',
    '&:hover': {
      borderColor: '#3CFFD0',
      color: '#3CFFD0',
      background: 'transparent',
    },
  },
}; 