export const blackSliderOverlayStyles = {
  sliderOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(17, 17, 17, 0.6)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    zIndex: 1300,
    transform: 'scaleY(0)',
    transformOrigin: 'top',
    opacity: 0,
    transition: 'transform 0.8s cubic-bezier(0.77, 0, 0.175, 1), opacity 0.5s cubic-bezier(0.77, 0, 0.175, 1)',
    cursor: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    p: { xs: 2, sm: 0 },
  },
  sliderOverlayOpen: {
    transform: 'scaleY(1)',
    opacity: 1,
  },
  sliderOverlayCursorDefault: {
    cursor: 'default',
  },
  searchFieldContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    background: 'transparent',
    padding: '0',
    border: 'none',
    outline: 'none',
    minWidth: { xs: '90vw', sm: 400 },
    maxWidth: { xs: '95vw', sm: 600 },
    width: '100%',
    margin: '0 auto',
    position: 'relative',
  },
  searchInput: {
    width: '100%',
    fontSize: { xs: 18, sm: 32, md: 48 },
    color: '#fff',
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid #3CFFD0',
    outline: 'none',
    padding: { xs: '12px 40px 12px 0', sm: '8px 48px 8px 0' },
    fontFamily: 'Montserrat, sans-serif',
    fontWeight: 400,
    '& .MuiInputBase-input': {
      fontSize: { xs: 18, sm: 32, md: 48 },
      color: '#fff',
      fontFamily: 'Montserrat, sans-serif',
      fontWeight: 400,
      padding: { xs: '8px 0', sm: '4px 0' },
    },
    '& .MuiInputBase-input::placeholder': {
      color: '#bdbdbd',
      opacity: 1,
      fontSize: { xs: 18, sm: 32, md: 48 },
    },
  },
  searchIcon: {
    position: 'absolute',
    right: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#fff',
    fontSize: { xs: 20, sm: 28, md: 36 },
    cursor: 'pointer',
    padding: { xs: 1, sm: 0.5 },
  },
  closeIcon: {
    position: 'absolute',
    top: { xs: 16, sm: 20, md: 24 },
    right: { xs: 16, sm: 24, md: 32 },
    color: '#fff',
    fontSize: { xs: 24, sm: 28, md: 36 },
    cursor: 'pointer',
    zIndex: 1400,
    transition: 'color 0.2s',
    padding: { xs: 1, sm: 0.5 },
    '&:hover': {
      color: '#3CFFD0',
    },
  },
}; 